const STATE = {
  AUTH: 'AUTH',
  NOT_AUTH: 'NOT_AUTH',
  SET_USER: 'SET_USER',
  SET_LOADING: 'SET_LOADING',
  CLEAR_LOADING: 'CLEAR_LOADING',
  SET_SIGNUP: 'SET_SIGNUP',
  SET_SIGNIN: 'SET_SIGNIN'
};

export default STATE;
